### PR TITLE
fixing create new robot bug

### LINKED ISSUE #199: [BUG] Create new robot
### Describe the bug
Upon creating a new robot and trying to open it, there should be the correct empty bpmn pool with a single start event loaded. In turn an error I sthrown.

### To Reproduce
1. Go to the robot overview and create a new bot from the button
2. Click on attempt to open the robot

### Expected behavior
The robot should open and render the preset BPMN from a ssot

### Additional context
The bug is caused by the 'create new robot' button not upserting the ssot to the database. Because opening the robot will attempt to retrieve the ssot by the specified id, it results in an error.

Please consider upserting (only) the ssot to the database upon creating a new robot.
Also consider possible problems which could be caused by the Id of the start event, as it will have the same Id as the normal start event, which by default will get deleted from the bpmn.

### PR DESCRIPTION
**Pull request by kej-jay**
closes #199 

## Changes
We now upset a custom start event to the spot in the database upon creation of a new robot through the interface.
Additionally there have been tests added to check, if the method behind the button to create a new robot is called correctly, as discussed. This is done by checking, if there have been correct calls through fetch to the backend, which are caused by the button press.

Sadly there are some errors, which are through through the included node modules because of camelcase vs lowercase, but nevertheless the test succeeds.

## Checklist before merge

**Developer's responsibilities**
* [ ] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [ ] **Pull request build** has passed
* [ ] **tested locally** (in at least chrome & firefox if frontend)
* [ ] updated the **documentation**
* [ ] added **tests** where necessary

### CODE REVIEW

File: client/src/components/content/RobotContainer/CreateRobotContainer.jsx [hunk 1]
```diff
@@ -14,30 +13,34 @@ const { Title } = Typography;
...
-
-                <Row justify="space-around" align="middle" style={{ height: '40%' }}>
-                    <Title className={styles.title} level={3} >
-                        Create new Robot
-                    </Title>
-                </Row>
-            </Col>
-        </Col >
-    )
+  const addRobot = () => props.createNewRobot();
```
Comment (WolfgangDaniel) [inline client/src/components/content/RobotContainer/CreateRobotContainer.jsx:16]: I know it is legacy code but it is better to use explicit properties for the class. So instead of props to use {createNewRobot} and than to use the function createNewRobot() without the props. before :)

File: client/src/components/pages/RobotOverview/RobotOverview.test.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+          throw new Error(`Unhandled request: ${url}`)
+        }
+    }
+}
+    
+beforeAll(() => jest.spyOn(window, 'fetch'))
+beforeEach(() => window.fetch.mockImplementation(mockFetch))
+
+describe('Testing functionality behind button to trigger function call for new but creation', () => {
+    it('check if attempt to fecth occured twice', async () => {
```
Comment (WolfgangDaniel) [inline client/src/components/pages/RobotOverview/RobotOverview.test.js:64]:
```suggestion
    it('check if attempt to fetch occured twice', async () => {    
```

**Review by WolfgangDaniel — CHANGES_REQUESTED** [review]
Two minor changes. Apart from that everything looks fine to me

File: client/src/components/pages/RobotOverview/RobotOverview.test.js [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+import {act, render, screen} from '@testing-library/react';
+import userEvent from '@testing-library/user-event';
+import { BrowserRouter } from 'react-router-dom';
+import RobotOverview from './RobotOverview';
+import '@testing-library/jest-dom'
+
+const USER_ID = '80625d115100a2ee8d8e695b';
+const NEW_ROBOT_NAME = 'New Robot';
+
+window.matchMedia = window.matchMedia || function() {
```
Comment (SanJSp) [inline client/src/components/pages/RobotOverview/RobotOverview.test.js:14]: Can you explain to me, what do the` || `do here? I haven't seen this yet 😄

File: client/src/components/pages/RobotOverview/RobotOverview.test.js [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+            // eslint-disable-next-line react/jsx-filename-extension
+            render(<BrowserRouter><RobotOverview /></BrowserRouter>);
+        });
+
+        act(() => {
+            userEvent.click(screen.getByText('Create new Robot'));
+        });
+        expect(window.fetch).toHaveBeenCalledTimes(2);
+    })
+})
```
Comment (SanJSp) [inline client/src/components/pages/RobotOverview/RobotOverview.test.js:75]:
```suggestion
})

```

File: client/src/components/pages/RobotOverview/RobotOverview.test.js [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+    
+beforeAll(() => jest.spyOn(window, 'fetch'))
+beforeEach(() => window.fetch.mockImplementation(mockFetch))
+
+describe('Testing functionality behind button to trigger function call for new but creation', () => {
+    it('check if attempt to fecth occured twice', async () => {    
+        act(() => {
+            // eslint-disable-next-line react/jsx-filename-extension
+            render(<BrowserRouter><RobotOverview /></BrowserRouter>);
+        });
```
Comment (SanJSp) [inline client/src/components/pages/RobotOverview/RobotOverview.test.js:68]: what does `act()` do?

**Review by SanJSp — CHANGES_REQUESTED** [review]
I'm a bit surprised about the 21K new lines of code in the package-lock 😲  maybe run `npm install` again and check if it's still that much? Otherwise, some small questions I'd like to understand 🙈

File: client/src/components/pages/RobotOverview/RobotOverview.test.js (hunk 3 above)
Comment (kej-jay) [reply client/src/components/pages/RobotOverview/RobotOverview.test.js:14]: Honestly no idea. I had an error saying window.matchMedia was undefined. Upon googling I found multiple approaches to solve it, this worked for me.
My understanding is that it works like „if window.matchMedia id defined use it, otherwise use the following function“

**Review by SanJSp — APPROVED** [review]

**Review by WolfgangDaniel — APPROVED** [review]
